# 数据加载
dataset_conf:
  use_raw: True # True使用原始音频数据，False使用特征数据
  # 训练数据路径列表
  train_list: 'datas/kws_datas/training_datas_modified.txt'
  # train_list: 'datas/kws_datas/train.npy'
  # 过滤最短的音频长度
  min_duration: 0.2
  # 最长的音频长度，大于这个长度会 裁剪掉 ?
  max_duration: 2.5
  # 音频的采样率
  sample_rate: 16000

  # 数据加载器参数
  dataLoader:
    # 训练的批量大小
    batch_size: 32
    # 读取数据的线程数量
    num_workers: 4
    # 是否丢弃最后一个样本
    drop_last: True

  # 是否使用SpecAug
  use_spec_aug: False
  # Spec增强参数
  spec_aug_args:
    # 随机频谱掩码大小
    freq_mask_width: [ 0, 8 ]
    # 随机时间掩码大小
    time_mask_width: [ 0, 10 ]

# 特征提取
preprocess_conf:
  # 特征提取的函数
  feature_method: 'FbankKaldi'
  # 特征提取的参数
  method_args:
    sample_frequency: 16000
    num_mel_bins: 40
    frame_length: 32.0
    frame_shift: 20.0
    high_freq: 0.0
    low_freq: 20.0
    preemphasis_coefficient: 0.0
    raw_energy: False
    remove_dc_offset: False
    use_power: True
    window_type: 'hanning'

# 优化函数
optimizer_conf:
  # 优化方法，支持Adam、AdamW、SGD
  optimizer: 'Adam'
  # 初始学习率的大小
  learning_rate: 0.002
  weight_decay: !!float 1e-5
  # scheduler支持 CosineAnnealingLR，WarmupCosineSchedulerLR
  scheduler: 'WarmupCosineSchedulerLR'
  # 学习率衰减函数参数
  scheduler_args:
    min_lr: !!float 1e-5
    max_lr: 0.002
    warmup_epoch: 5

# 训练超参数
train_conf:
  # 是否使用Pytorch2.0的编译器
  use_compile: True
  # 训练的轮数
  max_epoch: 100
  log_interval: 25

# 使用的模型
use_model: 'TCN2'
